name: Build

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Enable Corepack
      run: corepack enable
    - name: Install Rust Nightly
      run: rustup toolchain install nightly && rustup component add rustfmt --toolchain nightly
    - uses: extractions/setup-just@v1
    - name: Install `pandoc`
      run: sudo apt-get update && sudo apt-get install pandoc -y
    - name: Install `wasm-pack`
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Checkout Harper
      run: just pull-source
    - name: Build
      run: just build
    - name: Upload Artifact 
      uses: actions/upload-artifact@v4
      with: 
        name: harper-obsidian-plugin.zip
        path: harper-obsidian-plugin.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: harper/packages/obsidian-plugin/main.js,manifest.json
        allowUpdates: true
        draft: true
